my:
  greeting: Updated Testing From Config Server
  list:
    values: One, Two, Three, Four, Five

db:
  connection: connection-string-here-from-config-server
  host: 127.0.0.1
  port: 1200

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost

gateway:
   ip: 192.168.1.186
   
token:
   # 10 days
   expiration_time: 86400000
   secret: heyN0w619
